# -*- coding: utf-8 -*-
#
# Copyright (C) 2024-2025 Graz University of Technology.
#
# invenio-catalogue-marc21 is free software; you can redistribute it and/or
# modify it under the terms of the MIT License; see LICENSE file for more
# details.


name: CI

on:
  push:
    branches: master
  pull_request:
    branches:
      - master
      - "maint-**"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "0 3 * * 6"
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: false
        default: "Manual trigger"

jobs:
  python_tests:
    uses: inveniosoftware/workflows/.github/workflows/tests-python.yml@master
    with:
      python-version: '["3.12", "3.13"]'
  javascript_tests:
    uses: inveniosoftware/workflows/.github/workflows/tests-js.yml@master
